# Kode Untuk menampilkan data training
X_train


# Data Training
# Training set adalah bagian dataset yang kita latih untuk membuat prediksi atau algoritma ML lainnya sesuai tujuannya masing-masing.
# Kita memberikan petunjuk melalui algoritma agar mesin yang kita latih bisa mencari korelasinya sendiri.

# Hasil Data Training

# 48    I don't need your honestyIt's already in your ...
# 80    Inilah akhirnya harus kuakhiri Sebelum cintamu...
# 54    Tak mudah untuk kita Hadapi perbedaan yang ber...
# 73    A jaw dropperLooks good when he walksIs the su...
# 79    Forgive me first love, but I'm too tired.I'm b...
                            ...                        
# 85    Sayang, aku ingin berbicara kepadamu Tentang a...
# 67    Why is it every time I think I've tried my har...
# 64    will leave my heart at the door I won't say a ...
# 47    If this is my last night with youHold me like ...
# 44    Dirimu tak pernah menyadari Semua yang telah k...
# Name: text, Length: 66, dtype: object
