# Kode untuk menampilkan Data Test
X_test



# Test set adalah bagian dataset yang kita tes untuk melihat keakuratannya, atau dengan kata lain melihat performanya.



# Hasil dari Data Test

# 2     Di kala kau putus asa Dan telah lelah mencoba ...
# 13    biarkan saja kekasihmu pergi teruskan saja mim...
# 53    biarkan saja kekasihmu pergi teruskan saja mim...
# 41    Aku tak mengerti apa yang kurasa Rindu yang ta...
# 66    I don't need your honestyIt's already in your ...
# 30    Forgive me first love, but I'm too tired.I'm b...
# 45    Ku harus menemui cintaku Mencari tahu hubungan...
# 43    Namaku cinta, ketika kita bersamaBerbagi rasa ...
# 78    This love has dried up and stayed behind,And i...
# 88    Laguku ini tentang rindu ibu Pada saat ibu tak...
# 7     mimpi adalah kunci untuk kita menaklukkan duni...
# 26    telah lama kau tinggalkan ku sempat sia sia ka...
# 33    Day dreamer Sitting on the seaSoaking up the s...
# 63    Kau menyiksaku disini Dalam rasa bersalah yang...
# 8     Hanya bilik bambu tempat tinggal kita Tanpa hi...
# 16    Terlalu sadis caramu Menjadikan diriku Pelampi...
# 24    Bersabarlah, sayang Aku akan pulang Jangan den...
# 56    Terlalu sadis caramu Menjadikan diriku Pelampi...
# 77    Forgive me first love, but I'm tired.I need to...
# 42    telah lama kau tinggalkan ku sempat sia sia ka...
# 22    Tak mau lagi aku percaya Pada semua kasih saya...
# 6     Apa yang kau takutkan Dengan semua ini Bukanka...
# 61    nanti pasti kau sesali keputusan dirimu mening...
# Name: text, dtype: object
